#!/usr/bin/env bash
# Run this from the root directory

source ./test/approvals.bash

export PATH=.:$PATH

cli=ass

# Helps

describe "Help texts"
approve "$cli"
approve "$cli --help"

approve "$cli pkd"
approve "$cli pkd --help"

approve "$cli pkd aof"
approve "$cli pkd aof --help"

approve "$cli pkd aof list --help"

approve "$cli pkd proj"
approve "$cli pkd proj --help"

approve "$cli pkd proj list --help"

approve "$cli --version"

describe "pkd aof"
approve "$cli pkd aof ls --pkd-dir='test/resources/pkd'"

describe "pkd proj"
approve "$cli pkd proj ls --pkd-dir='test/resources/pkd'"

describe "todo append"
context "when appending 'Append test' to /tmp/ass_todo_append/todo.txt"
if [ -d "/tmp/ass_todo_append/" ];then
  rm -r "/tmp/ass_todo_append"
fi

mkdir /tmp/ass_todo_append
cp test/resources/todo/* /tmp/ass_todo_append/.

$cli todo append --todotxt-file /tmp/ass_todo_append/todo.txt "Append test"
approve "cat /tmp/ass_todo_append/todo.txt"

